# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrousuario():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrousuario(self):
    # Test name: Registro usuario
    # Step # | name | target | value
    # 1 | open | /auth/sign-in | 
    self.driver.get("https://test-qa.inlaze.com/auth/sign-in")
    # 2 | setWindowSize | 1354x714 | 
    self.driver.set_window_size(1354, 714)
    # 3 | click | linkText=Sign up | 
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    # 4 | click | linkText=Sign up | 
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    # 5 | click | id=full-name | 
    self.driver.find_element(By.ID, "full-name").click()
    # 6 | type | id=full-name | MARIA GOMEZ
    self.driver.find_element(By.ID, "full-name").send_keys("MARIA GOMEZ")
    # 7 | type | id=email | MGOMEZ@GMAIL.COM
    self.driver.find_element(By.ID, "email").send_keys("MGOMEZ@GMAIL.COM")
    # 8 | type | css=.w-full > #password | Pass123#
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > #password").send_keys("Pass123#")
    # 9 | click | css=.w-full > #confirm-password | 
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > #confirm-password").click()
    # 10 | type | css=.w-full > #confirm-password | Pass123#
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > #confirm-password").send_keys("Pass123#")
    # 11 | click | css=.btn:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
  
