# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginusuario():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginusuario(self):
    self.driver.get("https://test-qa.inlaze.com/auth/sign-in")
    self.driver.set_window_size(1354, 714)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("mgomezm555@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > #password").send_keys("Pass123#")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
  
